name = "husooblockless"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "husooblockless_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "husooblockless.wasm"
command = "npm run build:release"
